
% set image_dir and data_dir to your actual directories

%where the images are located
image_dir = 'scene_categories(1)'; 

%where to store the information generated by the process
data_dir = 'data3';
%where the renamed images are stored
newfolder = 'testFolder3';

%put all images in one folder relabeled.
categories = labelImages( image_dir , newfolder);

fnames = dir(fullfile(newfolder, '*.jpg'));
num_files = size(fnames,1);
filenames = cell(num_files,1);
labels = zeros(num_files,1);

%record the identification for each image
for f = 1:num_files
	filenames{f} = fnames(f).name;

    %record category label
    for i = 1: size(categories, 1)
        if(strcmp(filenames{f}(end - 7: end -4), categories{i}))
            labels(f) = i;
            i = size(categories, 1);
            
        end
    end
end

%control all the parameters
params.maxImageSize = 1000
params.dictionarySize = 300;
params.numTextonImages = 100 *(size(categories, 1) -2);
params.pyramidLevels = 3;

%commented out code to run the Spatial Pyramid code without LLC
% pyramid_all = BuildPyramid(filenames,newfolder,[data_dir],params,1);

% run the LLC code
pyramid_all = BuildPyramid2(filenames,newfolder,data_dir,params.maxImageSize,params.dictionarySize,params.numTextonImages,params.pyramidLevels,1);

name = [data_dir,'\pyramids_all_', num2str(params.dictionarySize), '_',num2str(params.pyramidLevels), '.mat'];
%perform SVM classification
SVMclass(name, labels, params.numTextonImages);
